---

- name: Create user-ca-bundle ConfigMap
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '{{ playbook_dir }}/roles/certs/templates/proxy-cert.yaml.j2') }}"

- name: Ensure proxy has correct bundle applied
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: Proxy
      metadata:
        name: cluster
      spec:
        trustedCA:
          name: user-ca-bundle
