---
- name: Deploy OpenShift Cluster on vSphere
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - deploy_cluster
  tasks:
    - debug:
        msg: "Deploy Cluster"

    - name: Create Cluster 
      include_role: 
        name: ocp_deploy_cluster
      vars:
        cluster_name: '{{ ocp_cluster.name }}'

