---
#################################################################################
############ Deploy OpenShift Cluster
#################################################################################
- name: Deploy OpenShift Cluster on vSphere
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - debug:
        msg: "Deploy Cluster"

    - name: Create Cluster
      include_role:
        name: ocp_deploy_cluster
      vars:
        cluster_name: '{{ ocp_cluster.name }}'

################################################################################
########### Post Cluster Deploy Tasks
################################################################################

#- import_playbook: "./cloud_providers/{{ cloud_provider }}/post_cluster.yaml"
#  vars:
#    cloud_provider: '{{ ocp_cluster.platform }}'
