---
- name: Get hosts for base plays
  hosts: localhost
  gather_facts: false

#- name: Perform base config
#  ansible.builtin.import_playbook:
#    base_playbook.yaml

- name: Configs for playbook
  hosts: localhost
  gather_facts: false

  # Uncomment K8S line if updating certs
  # Leave commented for initial cluster
  environment:
    # K8S_AUTH_SSL_CA_CERT: "{{ K8S_AUTH_SSL_CA_CERT }}"

  tasks:

    - name: Install GitOps Operator
      ansible.builtin.import_role:
        name: gitops
